apiVersion: v1
kind: Secret
metadata:
  name: {{ include "murmur.fullname" . }}
  labels:
    {{- include "murmur.labels" . | nindent 4 }}
data:
  {{- if .Values.database.password }}
  mysql-password: {{ .Values.database.password | b64enc }}
  {{- end }}
  {{- if .Values.config.serverPassword }}
  server-password: {{ .Values.config.serverPassword | b64enc }}
  {{- end }}