apiVersion: v1
kind: Service
metadata:
  name: {{ include "murmur.fullname" . }}
  labels:
    {{- include "murmur.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.port }}
      targetPort: udp
      protocol: UDP
      name: udp
  selector:
    {{- include "murmur.selectorLabels" . | nindent 4 }}
